language: node_js
node_js:
 - "node"

cache: npm
install: npm install

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 repo: laxative/f2e2nd_week1
 target_branch: gh-pages